import { z } from "zod"

/** The Flow JSON version every Mini App is exported as. */
export const MINI_APP_FLOW_JSON_VERSION = "7.3"

/** `flow_message_version` used when a published Mini App is sent on WhatsApp. */
export const MINI_APP_FLOW_MESSAGE_VERSION = "3"

export const miniAppComponentTypes = z.enum([
  "TextHeading",
  "TextSubheading",
  "TextBody",
  "TextCaption",
  "RichText",
  "TextInput",
  "TextArea",
  "Dropdown",
  "RadioButtonsGroup",
  "CheckboxGroup",
  "ChipsSelector",
  "DatePicker",
  "CalendarPicker",
  "OptIn",
  "PhotoPicker",
  "DocumentPicker",
  "Image",
  "ImageCarousel",
  "EmbeddedLink",
  "NavigationList",
  "Footer",
  "Form",
  "If",
  "Switch",
])
export type MiniAppComponentType = z.infer<typeof miniAppComponentTypes>

/**
 * Editor-side action. `navigate.next` holds the target screen's stable `key`
 * (not its Flow JSON id) so renaming a screen never breaks a link. Payloads
 * are generated by `toFlowJson`, never authored.
 */
export const miniAppActionSchema = z.discriminatedUnion("name", [
  z.object({ name: z.literal("navigate"), next: z.string().min(1) }),
  z.object({ name: z.literal("complete") }),
  z.object({ name: z.literal("open_url"), url: z.url() }),
])
export type MiniAppAction = z.infer<typeof miniAppActionSchema>
export type MiniAppActionName = MiniAppAction["name"]

export interface MiniAppNode {
  /**
   * Contact custom field that receives this input's answer. Editor-only: it is
   * never written to Flow JSON.
   */
  customFieldId?: string | null
  id: string
  /**
   * Flow JSON properties under their wire names (`"helper-text"`, …), except
   * the child slots. An `"on-click-action"` (on the node or inside a
   * NavigationList item) holds a `MiniAppAction`.
   */
  props: Record<string, unknown>
  /** Child slots: Form → `children`, If → `then`/`else`, Switch → one per case. */
  slots?: Record<string, MiniAppNode[]>
  type: MiniAppComponentType
}

export const miniAppNodeSchema: z.ZodType<MiniAppNode> = z.lazy(() =>
  z.object({
    id: z.string().min(1).max(64),
    type: miniAppComponentTypes,
    props: z.record(z.string(), z.unknown()),
    slots: z.record(z.string(), z.array(miniAppNodeSchema)).optional(),
    customFieldId: z.string().max(64).nullish(),
  }),
)

export const miniAppScreenSchema = z.object({
  /** Stable editor key, never exported. */
  key: z.string().min(1).max(64),
  /** Flow JSON screen id. */
  id: z.string().min(1).max(64),
  title: z.string().max(80).default(""),
  terminal: z.boolean().default(false),
  children: z.array(miniAppNodeSchema),
})
export type MiniAppScreen = z.infer<typeof miniAppScreenSchema>

export const MINI_APP_MAX_SCREENS = 100

export const miniAppDefinitionSchema = z.object({
  screens: z.array(miniAppScreenSchema).min(1).max(MINI_APP_MAX_SCREENS),
})
export type MiniAppDefinition = z.infer<typeof miniAppDefinitionSchema>

/** A loose Flow JSON object — Meta's wire format. */
export type FlowJsonComponent = { type: string } & Record<string, unknown>
export interface FlowJsonScreen {
  data?: Record<string, unknown>
  id: string
  layout: { type: "SingleColumnLayout"; children: FlowJsonComponent[] }
  success?: boolean
  terminal?: boolean
  title?: string
  [key: string]: unknown
}
export interface FlowJson {
  screens: FlowJsonScreen[]
  version: string
  [key: string]: unknown
}

export const flowJsonSchema = z
  .object({
    version: z.string(),
    screens: z
      .array(
        z
          .object({
            id: z.string(),
            title: z.string().optional(),
            terminal: z.boolean().optional(),
            layout: z
              .object({
                type: z.literal("SingleColumnLayout"),
                children: z.array(
                  z.looseObject({
                    type: z.string(),
                  }) as z.ZodType<FlowJsonComponent>,
                ),
              })
              .loose(),
          })
          .loose(),
      )
      .min(1)
      .max(MINI_APP_MAX_SCREENS),
  })
  .loose() as z.ZodType<FlowJson>
