import { T } from "@tolgee/react";
import { ArchiveIcon, BellIcon, BotIcon, CalculatorIcon, CalendarSyncIcon, ChartNoAxesCombinedIcon, CircleEllipsisIcon, ClockIcon, CodeIcon, CogIcon, CreditCardIcon, ImageIcon, ImagePlayIcon, KeyboardIcon, MessageCircleMoreIcon, MessageCirclePlusIcon, MessageCircleXIcon, MessagesSquareIcon, OctagonXIcon, PackageOpenIcon, PaperclipIcon, PictureInPicture2Icon, SaveIcon, SaveOffIcon, ShuffleIcon, StarIcon, StarOffIcon, TagIcon, TextIcon, UserIcon, UserRoundMinusIcon, UserRoundXIcon, VideoIcon, ZapIcon } from "lucide-react";
import { ReactElement } from "react";

export enum SendMessageEditorItem {
  Actions = "Actions",
  AddNotes = "AddNotes",
  AddTag = "AddTag",
  Archive = "Archive",
  AssignConversationToAnAdmin = "AssignConversationToAnAdmin",
  AutoAssignConversationToAnAdmin = "AutoAssignConversationToAnAdmin",
  BlockContact = "BlockContact",
  CancelPendingUserInput = "CancelPendingUserInput",
  Card = "Card",
  Carousel = "Carousel",
  CharacterCounter = "CharacterCounter",
  ClearCustomField = "ClearCustomField",
  DeleteContact = "DeleteContact",
  ExternalApiRequest = "ExternalApiRequest",
  File = "File",
  FileAudio = "FileAudio",
  FileOthers = "FileOthers",
  FindLocationsNearMe = "FindLocationsNearMe",
  FormatDate = "FormatDate",
  GenerateRandomNumberText = "GenerateRandomNumberText",
  GetDataFromJson = "GetDataFromJson",
  GetUserData = "GetUserData",
  Gif = "Gif",
  Image = "Image",
  Inbox = "Inbox",
  LogCustomEvents = "LogCustomEvents",
  MarkConversationAsFollowUp = "MarkConversationAsFollowUp",
  MoreOptions = "MoreOptions",
  NotifyAdmins = "NotifyAdmins",
  RemoveAssignment = "RemoveAssignment",
  RemoveConversationFromFollowUp = "RemoveConversationFromFollowUp",
  RemoveTag = "RemoveTag",
  SetCustomField = "SetCustomField",
  StartAnotherFlow = "StartAnotherFlow",
  StartAnotherStep = "StartAnotherStep",
  StartExternalStep = "StartExternalStep",
  SubscribeToReceiveBroadcasts = "SubscribeToReceiveBroadcasts",
  Text = "Text",
  Tools = "Tools",
  TransferConversationToBot = "TransferConversationToBot",
  TransferConversationToHuman = "TransferConversationToHuman",
  Trigger = "Trigger",
  TriggerMake = "TriggerMake",
  TriggerPabbly = "TriggerPabbly",
  TriggerZapier = "TriggerZapier",
  Typing = "Typing",
  Unarchive = "Unarchive",
  UnsubscribeFromAllBroadcast = "UnsubscribeFromAllBroadcast",
  Video = "Video",
}
export type SendMessageEditorItemType = keyof typeof SendMessageEditorItem

export type MenuItem = {
  label: ReactElement,
  icon: ReactElement,
  type: SendMessageEditorItemType,
  proFeature: boolean,
  children?: MenuItem[],
}

export const sendMessageEditorMenu: MenuItem[] = [
  {
    label: <T keyName="flows.sendMenuEditor.actions.Text" />,
    icon: <TextIcon />,
    type: SendMessageEditorItem.Text,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.Image" />,
    icon: <ImageIcon />,
    type: SendMessageEditorItem.Image,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.Card" />,
    icon: <CreditCardIcon />,
    type: SendMessageEditorItem.Card,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.Carousel" />,
    icon: <PictureInPicture2Icon />,
    type: SendMessageEditorItem.Carousel,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.GetUserData" />,
    icon: <KeyboardIcon />,
    type: SendMessageEditorItem.GetUserData,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.Video" />,
    icon: <VideoIcon />,
    type: SendMessageEditorItem.Video,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.Gif" />,
    icon: <ImagePlayIcon />,
    type: SendMessageEditorItem.Gif,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.Typing" />,
    icon: <ClockIcon />,
    type: SendMessageEditorItem.Typing,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.file" />,
    icon: <PaperclipIcon />,
    type: SendMessageEditorItem.File,
    proFeature: false,
  },
  {
    label: <T keyName="flows.sendMenuEditor.actions.Actions" />,
    icon: <ZapIcon />,
    type: SendMessageEditorItem.Actions,
    proFeature: false,
    children: [
      {
        label: <T keyName="flows.sendMenuEditor.actions.Inbox" />,
        icon: <MessagesSquareIcon />,
        type: SendMessageEditorItem.Inbox,
        proFeature: false,
        children: [
          {
            label: <T keyName="flows.sendMenuEditor.actions.TransferConversationToHuman" />,
            icon: <UserIcon />,
            type: SendMessageEditorItem.TransferConversationToHuman,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.TransferConversationToBot" />,
            icon: <BotIcon />,
            type: SendMessageEditorItem.TransferConversationToBot,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.AssignConversationToAnAdmin" />,
            icon: <MessageCirclePlusIcon />,
            type: SendMessageEditorItem.AssignConversationToAnAdmin,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.AutoAssignConversationToAnAdmin" />,
            icon: <MessageCirclePlusIcon />,
            type: SendMessageEditorItem.AutoAssignConversationToAnAdmin,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.RemoveAssignment" />,
            icon: <MessageCircleXIcon />,
            type: SendMessageEditorItem.RemoveAssignment,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.AddNotes" />,
            icon: <MessageCircleMoreIcon />,
            type: SendMessageEditorItem.AddNotes,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.MarkConversationAsFollowUp" />,
            icon: <StarIcon />,
            type: SendMessageEditorItem.MarkConversationAsFollowUp,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.RemoveConversationFromFollowUp" />,
            icon: <StarOffIcon />,
            type: SendMessageEditorItem.RemoveConversationFromFollowUp,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.Archive" />,
            icon: <ArchiveIcon />,
            type: SendMessageEditorItem.Archive,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.Unarchive" />,
            icon: <PackageOpenIcon />,
            type: SendMessageEditorItem.Unarchive,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.BlockContact" />,
            icon: <UserRoundMinusIcon />,
            type: SendMessageEditorItem.BlockContact,
            proFeature: false,
          },
        ]
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.AddTag" />,
        icon: <TagIcon />,
        type: SendMessageEditorItem.AddTag,
        proFeature: false,
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.RemoveTag" />,
        icon: <OctagonXIcon />,
        type: SendMessageEditorItem.RemoveTag,
        proFeature: false,
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.NotifyAdmins" />,
        icon: <BellIcon />,
        type: SendMessageEditorItem.NotifyAdmins,
        proFeature: false,
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.SetCustomField" />,
        icon: <SaveIcon />,
        type: SendMessageEditorItem.SetCustomField,
        proFeature: false,
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.ClearCustomField" />,
        icon: <SaveOffIcon />,
        type: SendMessageEditorItem.ClearCustomField,
        proFeature: false,
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.LogCustomEvents" />,
        icon: <ChartNoAxesCombinedIcon />,
        type: SendMessageEditorItem.LogCustomEvents,
        proFeature: false,
      },
      // {
      //   label: <T keyName="flows.sendMenuEditor.actions.SubscribeToReceiveBroadcasts" />,
      //   icon: <ZapIcon />,
      //   type: SendMessageEditorItem.SubscribeToReceiveBroadcasts,
      //   proFeature: false,
      // },
      // {
      //   label: <T keyName="flows.sendMenuEditor.actions.UnsubscribeFromAllBroadcast" />,
      //   icon: <ZapOffIcon />,
      //   type: SendMessageEditorItem.UnsubscribeFromAllBroadcast,
      //   proFeature: false,
      // },
      {
        label: <T keyName="flows.sendMenuEditor.actions.DeleteContact" />,
        icon: <UserRoundXIcon />,
        type: SendMessageEditorItem.DeleteContact,
        proFeature: false,
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.ExternalApiRequest" />,
        icon: <CodeIcon />,
        type: SendMessageEditorItem.ExternalApiRequest,
        proFeature: false,
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.Trigger" />,
        icon: <ZapIcon />,
        type: SendMessageEditorItem.Trigger,
        proFeature: false,
        children: [
          {
            label: <T keyName="flows.sendMenuEditor.actions.TriggerZapier" />,
            icon: <ZapIcon />,
            type: SendMessageEditorItem.TriggerZapier,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.TriggerMake" />,
            icon: <ZapIcon />,
            type: SendMessageEditorItem.TriggerMake,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.TriggerPabbly" />,
            icon: <ZapIcon />,
            type: SendMessageEditorItem.TriggerPabbly,
            proFeature: false,
          },
        ]
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.MoreOptions" />,
        icon: <CircleEllipsisIcon />,
        type: SendMessageEditorItem.MoreOptions,
        proFeature: false,
        children: [
          // {
          //   label: <T keyName="flows.sendMenuEditor.actions.FindLocationsNearMe" />,
          //   icon: <MapPinnedIcon />,
          //   type: SendMessageEditorItem.FindLocationsNearMe,
          //   proFeature: false,
          // },
          {
            label: <T keyName="flows.sendMenuEditor.actions.StartAnotherFlow" />,
            icon: <ZapIcon />,
            type: SendMessageEditorItem.StartAnotherFlow,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.StartAnotherStep" />,
            icon: <ZapIcon />,
            type: SendMessageEditorItem.StartAnotherStep,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.StartExternalStep" />,
            icon: <ZapIcon />,
            type: SendMessageEditorItem.StartExternalStep,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.CancelPendingUserInput" />,
            icon: <ZapIcon />,
            type: SendMessageEditorItem.CancelPendingUserInput,
            proFeature: false,
          },
        ]
      },
      {
        label: <T keyName="flows.sendMenuEditor.actions.Tools" />,
        icon: <CogIcon />,
        type: SendMessageEditorItem.Tools,
        proFeature: false,
        children: [
          {
            label: <T keyName="flows.sendMenuEditor.actions.GetDataFromJson" />,
            icon: <CodeIcon />,
            type: SendMessageEditorItem.GetDataFromJson,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.FormatDate" />,
            icon: <CalendarSyncIcon />,
            type: SendMessageEditorItem.FormatDate,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.GenerateRandomNumberText" />,
            icon: <ShuffleIcon />,
            type: SendMessageEditorItem.GenerateRandomNumberText,
            proFeature: false,
          },
          {
            label: <T keyName="flows.sendMenuEditor.actions.CharacterCounter" />,
            icon: <CalculatorIcon />,
            type: SendMessageEditorItem.CharacterCounter,
            proFeature: false,
          },
        ]
      },
    ]
  },
]
