import { InboxType, OMNICHANNEL } from "@aha.chat/database/types"
import { createId } from "@paralleldrive/cuid2"
import { z } from "zod"
import {
  addContactTagStepSchema,
  addNotesStepSchema,
  archiveConversationStepSchema,
  assignConversationStepSchema,
  autoAssignConversationStepSchema,
  blockContactStepSchema,
  claudeGenerateTextSchema,
  clearCustomFieldStepSchema,
  countCharactersStepSchema,
  deepseekGenerateTextSchema,
  deleteContactStepSchema,
  disableBotStepSchema,
  enableBotStepSchema,
  followConversationStepSchema,
  formatDateStepSchema,
  geminiGenerateTextSchema,
  generateCodeStepSchema,
  getDataFromJsonStepSchema,
  markEmailVerifiedStepSchema,
  openAIAnalyzeImageSchema,
  openAIDeleteMessageHistorySchema,
  openAIGenerateImageSchema,
  openAIGenerateTextAgentSchema,
  openAIGenerateTextAssistantSchema,
  openAIGenerateTextSchema,
  openAISpeechToTextSchema,
  openAITextToSpeechSchema,
  optInEmailStepSchema,
  optOutEmailStepSchema,
  removeContactTagStepSchema,
  sendAudioStepSchema,
  sendFileStepSchema,
  sendImageStepSchema,
  sendTextStepSchema,
  sendVideoStepSchema,
  setCustomFieldStepSchema,
  unarchiveConversationStepSchema,
  unassignConversationStepSchema,
  unfollowConversationStepSchema,
} from "../steps"
import { baseNodeSchema, type NewNodeProps, NodeType } from "./node-config"

export const actionsStepSchema = [
  // Open AI
  openAIGenerateTextSchema,
  openAIGenerateTextAgentSchema,
  openAIGenerateTextAssistantSchema,
  openAIGenerateImageSchema,
  openAIAnalyzeImageSchema,
  openAISpeechToTextSchema,
  openAITextToSpeechSchema,
  openAIDeleteMessageHistorySchema,

  // Email
  markEmailVerifiedStepSchema,
  optInEmailStepSchema,
  optOutEmailStepSchema,
]

export const sendMessageNodeSchema = baseNodeSchema.extend({
  type: z.literal(NodeType.SendMessage),
  data: z.object({
    name: z.string().trim().min(1).max(255),
    isStartNode: z.boolean(),
    inboxType: z.union([z.enum(InboxType), z.literal(OMNICHANNEL)]),
    steps: z.array(
      z.union([
        addNotesStepSchema,
        archiveConversationStepSchema,
        assignConversationStepSchema,
        autoAssignConversationStepSchema,
        blockContactStepSchema,
        clearCustomFieldStepSchema,
        countCharactersStepSchema,
        disableBotStepSchema,
        enableBotStepSchema,
        followConversationStepSchema,
        formatDateStepSchema,
        generateCodeStepSchema,
        getDataFromJsonStepSchema,
        markEmailVerifiedStepSchema,
        optInEmailStepSchema,
        optOutEmailStepSchema,
        sendImageStepSchema,
        sendTextStepSchema,
        setCustomFieldStepSchema,
        unarchiveConversationStepSchema,
        unassignConversationStepSchema,
        unfollowConversationStepSchema,
        addContactTagStepSchema,
        removeContactTagStepSchema,
        deleteContactStepSchema,
        sendFileStepSchema,
        // sendCardStepSchema,
        sendVideoStepSchema,
        sendAudioStepSchema,
        sendFileStepSchema,
        // OpenAI Steps
        openAIGenerateTextSchema,
        openAIGenerateTextAgentSchema,
        openAIGenerateTextAssistantSchema,
        openAIGenerateImageSchema,
        openAIAnalyzeImageSchema,
        openAISpeechToTextSchema,
        openAITextToSpeechSchema,
        openAIDeleteMessageHistorySchema,
        geminiGenerateTextSchema,
        claudeGenerateTextSchema,
        deepseekGenerateTextSchema,
        // sendCarouselStepSchema,
      ]),
    ),
  }),
})
export type SendMessageNodeSchema = z.infer<typeof sendMessageNodeSchema>

export const sendMessageNodeDefaultFn = ({
  labelVersion,
  ...props
}: NewNodeProps): SendMessageNodeSchema => ({
  id: createId(),
  type: NodeType.SendMessage,
  measured: { width: 288, height: 100 },
  ...props,
  data: {
    name: `Send Message #${labelVersion}`,
    inboxType: OMNICHANNEL,
    isStartNode: false,
    steps: [],
  },
})
