import { z } from "zod"

export const templateTypes = z.enum([
  "Text",
  "Image",
  "Video",
  "Document",
  "CarouselImage",
  "CarouselVideo",
  "Location",
  "ViewCatalog",
  "ViewProduct",
])
export type TemplateType = z.infer<typeof templateTypes>

export const languageOptions = [
  { label: "Africâner", value: "af" },
  { label: "Albanês", value: "sq" },
  { label: "Árabe", value: "ar" },
  { label: "Árabe (EGY)", value: "ar_EG" },
  { label: "Árabe (UAE)", value: "ar_AE" },
  { label: "Árabe (LBN)", value: "ar_LB" },
  { label: "Árabe (MAR)", value: "ar_MA" },
  { label: "Árabe (QAT)", value: "ar_QA" },
  { label: "Azerbaijano", value: "az" },
  { label: "Bielorrusso", value: "be_BY" },
  { label: "Bengali", value: "bn" },
  { label: "Bengali (IND)", value: "bn_IN" },
  { label: "Búlgaro", value: "bg" },
  { label: "Catalão", value: "ca" },
  { label: "Chinês (CHN)", value: "zh_CN" },
  { label: "Chinês (HKG)", value: "zh_HK" },
  { label: "Chinês (TAI)", value: "zh_TW" },
  { label: "Croata", value: "hr" },
  { label: "Tcheco", value: "cs" },
  { label: "Dinamarquês", value: "da" },
  { label: "Dari", value: "prs_AF" },
  { label: "Holandês", value: "nl" },
  { label: "Holandês (BEL)", value: "nl_BE" },
  { label: "Inglês", value: "en" },
  { label: "Inglês (UK)", value: "en_GB" },
  { label: "Inglês (US)", value: "en_US" },
  { label: "Inglês (UAE)", value: "en_AE" },
  { label: "Inglês (AUS)", value: "en_AU" },
  { label: "Inglês (CAN)", value: "en_CA" },
  { label: "Inglês (GHA)", value: "en_GH" },
  { label: "Inglês (IRL)", value: "en_IE" },
  { label: "Inglês (IND)", value: "en_IN" },
  { label: "Inglês (JAM)", value: "en_JM" },
  { label: "Inglês (MYS)", value: "en_MY" },
  { label: "Inglês (NZL)", value: "en_NZ" },
  { label: "Inglês (QAT)", value: "en_QA" },
  { label: "Inglês (SGP)", value: "en_SG" },
  { label: "Inglês (UGA)", value: "en_UG" },
  { label: "Inglês (ZAF)", value: "en_ZA" },
  { label: "Estoniano", value: "et" },
  { label: "Filipino", value: "fil" },
  { label: "Finlandês", value: "fi" },
  { label: "Francês", value: "fr" },
  { label: "Francês (BEL)", value: "fr_BE" },
  { label: "Francês (CAN)", value: "fr_CA" },
  { label: "Francês (CHE)", value: "fr_CH" },
  { label: "Francês (CIV)", value: "fr_CI" },
  { label: "Francês (MAR)", value: "fr_MA" },
  { label: "Georgiano", value: "ka" },
  { label: "Alemão", value: "de" },
  { label: "Alemão (AUT)", value: "de_AT" },
  { label: "Alemão (CHE)", value: "de_CH" },
  { label: "Grego", value: "el" },
  { label: "Gujarati", value: "gu" },
  { label: "Hauçá", value: "ha" },
  { label: "Hebraico", value: "he" },
  { label: "Hindi", value: "hi" },
  { label: "Húngaro", value: "hu" },
  { label: "Indonésio", value: "id" },
  { label: "Irlandês", value: "ga" },
  { label: "Italiano", value: "it" },
  { label: "Japonês", value: "ja" },
  { label: "Canarês", value: "kn" },
  { label: "Cazaque", value: "kk" },
  { label: "Quiniaruanda", value: "rw_RW" },
  { label: "Coreano", value: "ko" },
  { label: "Quirguiz (Quirguistão)", value: "ky_KG" },
  { label: "Laosiano", value: "lo" },
  { label: "Letão", value: "lv" },
  { label: "Lituano", value: "lt" },
  { label: "Macedônio", value: "mk" },
  { label: "Malaio", value: "ms" },
  { label: "Malaiala", value: "ml" },
  { label: "Marata", value: "mr" },
  { label: "Norueguês", value: "nb" },
  { label: "Pachto", value: "ps_AF" },
  { label: "Persa", value: "fa" },
  { label: "Polonês", value: "pl" },
  { label: "Português (BR)", value: "pt_BR" },
  { label: "Português (POR)", value: "pt_PT" },
  { label: "Panjabi", value: "pa" },
  { label: "Romeno", value: "ro" },
  { label: "Russo", value: "ru" },
  { label: "Sérvio", value: "sr" },
  { label: "Cingalês", value: "si_LK" },
  { label: "Eslovaco", value: "sk" },
  { label: "Esloveno", value: "sl" },
  { label: "Espanhol", value: "es" },
  { label: "Espanhol (ARG)", value: "es_AR" },
  { label: "Espanhol (CHL)", value: "es_CL" },
  { label: "Espanhol (COL)", value: "es_CO" },
  { label: "Espanhol (CRI)", value: "es_CR" },
  { label: "Espanhol (DOM)", value: "es_DO" },
  { label: "Espanhol (ECU)", value: "es_EC" },
]
