-- Migration 3/3 of the `outcome` rollout (review A-HIGH). Split out from what
-- used to be the last statement of
-- 20260917173245_whatsapp_call_outcome_backfill_index so a retry can never
-- observe zero covering indexes on `WhatsappCall`.
--
-- By the time this migration is even eligible to run, migration 2/3 has
-- already completed in full and been recorded by the runner
-- (`scripts/run-migrations.mjs` only inserts a migration's `__drizzle_migrations`
-- row after every one of its statements succeeds, and applies migrations in
-- folder-timestamp order) — so the new
-- `WhatsappCall_workspaceId_createdAt_id_idx` is guaranteed to already exist
-- and be VALID before this file's single statement ever executes. This file
-- therefore only ever needs to remove the now-redundant old index; it never
-- creates or touches the new one, so a crash-and-retry of THIS file alone
-- can only re-run the same idempotent drop — the new index is never at risk
-- of being rebuilt or removed by this migration.
--
-- Uses `CONCURRENTLY` (no SHARE lock, no blocked inserts), so the runner
-- executes this file UNWRAPPED — no transaction, no ACCESS EXCLUSIVE lock.
-- `IF EXISTS` makes the single statement idempotent/safe to re-run.
DROP INDEX CONCURRENTLY IF EXISTS "WhatsappCall_workspaceId_createdAt_idx";
