import type {
  MiniAppActionName,
  MiniAppComponentCategory,
  MiniAppComponentType,
  MiniAppDefaultTextKey,
  MiniAppIssueCode,
} from "@chatbotx.io/mini-app"

// Exhaustive literal maps so every translation key stays greppable and an
// unmapped enum member is a type error.

export const componentLabelKey = {
  TextHeading: "miniApps.components.TextHeading",
  TextSubheading: "miniApps.components.TextSubheading",
  TextBody: "miniApps.components.TextBody",
  TextCaption: "miniApps.components.TextCaption",
  RichText: "miniApps.components.RichText",
  TextInput: "miniApps.components.TextInput",
  TextArea: "miniApps.components.TextArea",
  Dropdown: "miniApps.components.Dropdown",
  RadioButtonsGroup: "miniApps.components.RadioButtonsGroup",
  CheckboxGroup: "miniApps.components.CheckboxGroup",
  ChipsSelector: "miniApps.components.ChipsSelector",
  DatePicker: "miniApps.components.DatePicker",
  CalendarPicker: "miniApps.components.CalendarPicker",
  OptIn: "miniApps.components.OptIn",
  PhotoPicker: "miniApps.components.PhotoPicker",
  DocumentPicker: "miniApps.components.DocumentPicker",
  Image: "miniApps.components.Image",
  ImageCarousel: "miniApps.components.ImageCarousel",
  EmbeddedLink: "miniApps.components.EmbeddedLink",
  NavigationList: "miniApps.components.NavigationList",
  Footer: "miniApps.components.Footer",
  Form: "miniApps.components.Form",
  If: "miniApps.components.If",
  Switch: "miniApps.components.Switch",
} as const satisfies Record<MiniAppComponentType, string>

export const categoryLabelKey = {
  text: "miniApps.categories.text",
  input: "miniApps.categories.input",
  selection: "miniApps.categories.selection",
  media: "miniApps.categories.media",
  navigation: "miniApps.categories.navigation",
  container: "miniApps.categories.container",
} as const satisfies Record<MiniAppComponentCategory, string>

export const actionLabelKey = {
  navigate: "miniApps.actions.navigate",
  complete: "miniApps.actions.complete",
  open_url: "miniApps.actions.open_url",
} as const satisfies Record<MiniAppActionName, string>

export const defaultTextKey = {
  heading: "miniApps.defaults.heading",
  subheading: "miniApps.defaults.subheading",
  body: "miniApps.defaults.body",
  caption: "miniApps.defaults.caption",
  richText: "miniApps.defaults.richText",
  textInputLabel: "miniApps.defaults.textInputLabel",
  textAreaLabel: "miniApps.defaults.textAreaLabel",
  dropdownLabel: "miniApps.defaults.dropdownLabel",
  radioLabel: "miniApps.defaults.radioLabel",
  checkboxLabel: "miniApps.defaults.checkboxLabel",
  chipsLabel: "miniApps.defaults.chipsLabel",
  dateLabel: "miniApps.defaults.dateLabel",
  calendarLabel: "miniApps.defaults.calendarLabel",
  optInLabel: "miniApps.defaults.optInLabel",
  photoLabel: "miniApps.defaults.photoLabel",
  documentLabel: "miniApps.defaults.documentLabel",
  linkText: "miniApps.defaults.linkText",
  footerLabel: "miniApps.defaults.footerLabel",
  option: "miniApps.defaults.option",
  navigationItem: "miniApps.defaults.navigationItem",
  imageAlt: "miniApps.defaults.imageAlt",
} as const satisfies Record<MiniAppDefaultTextKey, string>

export const issueLabelKey = {
  definition_invalid: "miniApps.issues.definition_invalid",
  screen_id_invalid: "miniApps.issues.screen_id_invalid",
  screen_id_reserved: "miniApps.issues.screen_id_reserved",
  screen_id_duplicate: "miniApps.issues.screen_id_duplicate",
  no_terminal_screen: "miniApps.issues.no_terminal_screen",
  terminal_screen_without_complete:
    "miniApps.issues.terminal_screen_without_complete",
  screen_without_exit: "miniApps.issues.screen_without_exit",
  screen_unreachable: "miniApps.issues.screen_unreachable",
  too_many_components: "miniApps.issues.too_many_components",
  component_limit: "miniApps.issues.component_limit",
  picker_conflict: "miniApps.issues.picker_conflict",
  picker_multiple_in_complete: "miniApps.issues.picker_multiple_in_complete",
  footer_not_last: "miniApps.issues.footer_not_last",
  footer_in_nested_branch: "miniApps.issues.footer_in_nested_branch",
  footer_missing_in_branch: "miniApps.issues.footer_missing_in_branch",
  navigation_list_with_footer: "miniApps.issues.navigation_list_with_footer",
  navigation_list_on_terminal: "miniApps.issues.navigation_list_on_terminal",
  if_too_deep: "miniApps.issues.if_too_deep",
  if_then_empty: "miniApps.issues.if_then_empty",
  switch_no_cases: "miniApps.issues.switch_no_cases",
  child_not_allowed: "miniApps.issues.child_not_allowed",
  name_invalid: "miniApps.issues.name_invalid",
  name_duplicate: "miniApps.issues.name_duplicate",
  property_required: "miniApps.issues.property_required",
  property_too_long: "miniApps.issues.property_too_long",
  property_too_short: "miniApps.issues.property_too_short",
  property_invalid: "miniApps.issues.property_invalid",
  option_duplicate_id: "miniApps.issues.option_duplicate_id",
  min_greater_than_max: "miniApps.issues.min_greater_than_max",
  action_required: "miniApps.issues.action_required",
  action_not_allowed: "miniApps.issues.action_not_allowed",
  navigate_target_missing: "miniApps.issues.navigate_target_missing",
  navigate_self: "miniApps.issues.navigate_self",
  expression_invalid: "miniApps.issues.expression_invalid",
  reference_invalid: "miniApps.issues.reference_invalid",
  reference_unknown: "miniApps.issues.reference_unknown",
  data_reference_unsupported: "miniApps.issues.data_reference_unsupported",
  property_unknown: "miniApps.issues.property_unknown",
  complete_on_non_terminal: "miniApps.issues.complete_on_non_terminal",
  footer_captions_invalid: "miniApps.issues.footer_captions_invalid",
  options_with_images_limit: "miniApps.issues.options_with_images_limit",
  navigation_badge_multiple: "miniApps.issues.navigation_badge_multiple",
} as const satisfies Record<MiniAppIssueCode, string>

/** Inspector labels per Flow JSON property name. */
export const propertyLabelKey = {
  text: "miniApps.properties.text",
  label: "miniApps.properties.label",
  name: "miniApps.properties.name",
  description: "miniApps.properties.description",
  title: "miniApps.properties.title",
  required: "miniApps.properties.required",
  "helper-text": "miniApps.properties.helperText",
  "error-message": "miniApps.properties.errorMessage",
  "init-value": "miniApps.properties.initValue",
  "input-type": "miniApps.properties.inputType",
  "label-variant": "miniApps.properties.labelVariant",
  pattern: "miniApps.properties.pattern",
  "min-chars": "miniApps.properties.minChars",
  "max-chars": "miniApps.properties.maxChars",
  "max-length": "miniApps.properties.maxLength",
  "font-weight": "miniApps.properties.fontWeight",
  strikethrough: "miniApps.properties.strikethrough",
  markdown: "miniApps.properties.markdown",
  "data-source": "miniApps.properties.dataSource",
  "media-size": "miniApps.properties.mediaSize",
  "min-selected-items": "miniApps.properties.minSelectedItems",
  "max-selected-items": "miniApps.properties.maxSelectedItems",
  "min-date": "miniApps.properties.minDate",
  "max-date": "miniApps.properties.maxDate",
  "unavailable-dates": "miniApps.properties.unavailableDates",
  mode: "miniApps.properties.mode",
  "min-days": "miniApps.properties.minDays",
  "max-days": "miniApps.properties.maxDays",
  "include-days": "miniApps.properties.includeDays",
  "photo-source": "miniApps.properties.photoSource",
  "min-uploaded-photos": "miniApps.properties.minUploadedPhotos",
  "max-uploaded-photos": "miniApps.properties.maxUploadedPhotos",
  "min-uploaded-documents": "miniApps.properties.minUploadedDocuments",
  "max-uploaded-documents": "miniApps.properties.maxUploadedDocuments",
  "max-file-size-kb": "miniApps.properties.maxFileSizeKb",
  "allowed-mime-types": "miniApps.properties.allowedMimeTypes",
  src: "miniApps.properties.src",
  width: "miniApps.properties.width",
  height: "miniApps.properties.height",
  "scale-type": "miniApps.properties.scaleType",
  "aspect-ratio": "miniApps.properties.aspectRatio",
  "alt-text": "miniApps.properties.altText",
  images: "miniApps.properties.images",
  "list-items": "miniApps.properties.listItems",
  "left-caption": "miniApps.properties.leftCaption",
  "center-caption": "miniApps.properties.centerCaption",
  "right-caption": "miniApps.properties.rightCaption",
  enabled: "miniApps.properties.enabled",
  condition: "miniApps.properties.condition",
  value: "miniApps.properties.value",
  "on-click-action": "miniApps.properties.action",
  id: "miniApps.properties.screenId",
} as const

export type MiniAppPropertyKey = keyof typeof propertyLabelKey

export const isPropertyKey = (key: string): key is MiniAppPropertyKey =>
  key in propertyLabelKey

/** Translation keys for enum-valued properties. */
export const enumOptionLabelKey = {
  "input-type": {
    text: "miniApps.options.inputType.text",
    number: "miniApps.options.inputType.number",
    email: "miniApps.options.inputType.email",
    password: "miniApps.options.inputType.password",
    passcode: "miniApps.options.inputType.passcode",
    phone: "miniApps.options.inputType.phone",
  },
  "font-weight": {
    normal: "miniApps.options.fontWeight.normal",
    bold: "miniApps.options.fontWeight.bold",
    italic: "miniApps.options.fontWeight.italic",
    bold_italic: "miniApps.options.fontWeight.bold_italic",
  },
  "scale-type": {
    cover: "miniApps.options.scaleType.cover",
    contain: "miniApps.options.scaleType.contain",
  },
  "media-size": {
    regular: "miniApps.options.mediaSize.regular",
    large: "miniApps.options.mediaSize.large",
  },
  mode: {
    single: "miniApps.options.mode.single",
    range: "miniApps.options.mode.range",
  },
  "photo-source": {
    camera_gallery: "miniApps.options.photoSource.camera_gallery",
    camera: "miniApps.options.photoSource.camera",
    gallery: "miniApps.options.photoSource.gallery",
  },
  "include-days": {
    Mon: "miniApps.options.weekday.Mon",
    Tue: "miniApps.options.weekday.Tue",
    Wed: "miniApps.options.weekday.Wed",
    Thu: "miniApps.options.weekday.Thu",
    Fri: "miniApps.options.weekday.Fri",
    Sat: "miniApps.options.weekday.Sat",
    Sun: "miniApps.options.weekday.Sun",
  },
} as const

export type EnumPropertyKey = keyof typeof enumOptionLabelKey
